version: '3.2'

services:
  build:
    build: .
    volumes:
      - ./configuration.nix:/configuration.nix:ro
      - ./out:/out
    privileged: true
    command: sh -c "nixos-generate -f raw -c /configuration.nix; cp -r /nix/store/*-nixos-disk-image/* /out; chmod -R 777 /out"