version: '3.2'

services:
  build:
    build: .
    volumes:
      - ./configuration.nix:/configuration.nix:ro
      - ./format.nix:/format.nix:ro
      - ./out:/out
    privileged: true
    command: sh -c "nixos-generate --format-path /format.nix -c /configuration.nix; rm /out/*; cp -r /nix/store/*-nixos-disk-image/* /out; chmod -R 777 /out"