version: '3.2'

services:
  build:
    build: .
    volumes:
      - ./appliance.nix:/appliance.nix:ro
      - ./out:/out
    command: sh -c "nixos-generate -f raw -c /appliance.nix; cp -r /result/* /out"